language: rust
cache: cargo
dist: trusty
os: 
  - linux

# Run builds for all the supported trains
rust:
  - stable

before_script:
    - sudo apt-get update
    - sudo apt-get install -y libegl1-mesa-dev libgles2-mesa-dev
    - sudo apt-get install -y libasound2-dev libsdl2-dev pkg-config
    - rustup component add rustfmt-preview
    - rustup component add clippy-preview
script:
    - cargo fmt --all -- --check
    - cargo clippy
    - cargo build
    - cargo test

# Upload docs
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo rustdoc -- --no-defaults --passes collapse-docs --passes unindent-comments &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
