sudo: true
language: rust
cache: cargo
dist: trusty
os: 
  - linux
  - osx

# Run builds for all the supported trains
rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-get -qq update
      && sudo apt-get install -y libasound2-dev;
    fi

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      wget http://libsdl.org/release/SDL2-2.0.5.tar.gz
      && tar -xzvf SDL2-2.0.5.tar.gz
      && pushd SDL2-2.0.5 && ./configure --prefix=/usr && make && sudo make install && popd;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update
      && brew install sdl2;
    fi

before_script:
    - rustup component add rustfmt-preview
    - rustup component add clippy-preview
script:
    - cargo fmt --all -- --check
    - cargo clippy
    - cargo build
    - cargo test

# Upload docs
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo rustdoc -- --no-defaults --passes collapse-docs --passes unindent-comments &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
