language: rust
cache: cargo
rust:
- nightly
before_script: "(cargo install rustfmt || true)"
script:
- cargo fmt -- --write-mode=diff && cargo build && cargo test
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo rustdoc -- --no-defaults --passes collapse-docs --passes unindent-comments &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
